basedosdados/queries-basedosdados

- models/br_bcb_agencia/br_bcb_agencia__agencia_atualizado.sql
- models/br_bcb_agencia/schema.yml
> [dbt] br_bcb_agencia

- models/br_rf_cafir/br_rf_cafir__imoveis_rurais.sql
- corrige subqueries do modelo imoveis_rurais
> [fix-dbt] `br_rf_cafir`

- models/br_cvm_administradores_carteira/br_cvm_administradores_carteira__pessoa_fisica.sql
- models/br_cvm_administradores_carteira/br_cvm_administradores_carteira__pessoa_juridica.sql
- models/br_cvm_administradores_carteira/br_cvm_administradores_carteira__responsavel.sql
- models/br_cvm_administradores_carteira/pessoa_fisica.sql
- models/br_cvm_administradores_carteira/schema.yml
- models/br_cvm_oferta_publica_distribuicao/br_cvm_oferta_publica_distribuicao__dia.sql
- models/br_cvm_oferta_publica_distribuicao/schema.yml
- Registra novos modelos dbt de:
1. `br_cvm_administradores_carteira`
2. `br_cvm_oferta_publica_distribuicao`
> [dbt] `br_cvm`

- models/br_me_caged/microdados_movimentacao.sql
- models/br_me_caged/microdados_movimentacao_excluida.sql
- models/br_me_caged/microdados_movimentacao_fora_prazo.sql
Resolvendo o problema apontado por: 
```
Nome: Tiago
Sobrenome: Moutta
Email: tiago.moutta@kapitalo.com.br
Assunto: Dados
Mensagem: Olá, eu uso a base dos dados para extrair os micro dados do caged, porém nesta última divulgação notei uma inconsistência no que tange as horas contratadas. Está tudo como #NA. Isso é problema do próprio arquivo enviado pelo ministério do trabalho ou seria alguma questão interna da base dos dados? Agradeço a atenção
```
O formato da coluna `horas_contratuais` mudou do mês 7 para o mês 8.
> [dbt] br_me_caged

- dbt_project.yml
- models/br_inpe_prodes/br_inpe_prodes_desmatamento_municipio.sql
- models/br_inpe_prodes/code/clean_data.py
- models/br_inpe_prodes/code/download_data.py
- models/br_inpe_prodes/schema.yaml
PR referente à issue #157 
Inicialmente era apenas para atualizar o conjunto de dados com o ano de 2022. 
Porém, ocorreu uma mudança na estrutura dos dados disponibilizados pela [Prodes](https://www.dpi.inpe.br/prodesdigital/prodesmunicipal.php) E agora o PR está mandando o conjunto de dados com cobertura de 2000 a 2022 com a nova estrutura disponível. 🤞
> [dados] br_inpe_prodes

- models/br_inep_enem/br_inep_enem__dicionario.sql
- models/br_inep_enem/code/main.py
Muitos valores da coluna `cobertura_temporal` para a tabela `microdados` em `basedosdados.br_inep_enem.dicionario` estavam como `null`.
Close #336
> [dbt] fix br_inep_enem.dicionario

- models/br_ibge_pnadc/br_ibge_pnadc__microdados.sql
Resolvendo o problema reportado pela @vilelaluiza:
> [fix]: add Jinja code to clean string columns in `br_ibge_pnadc.microdados`

- dbt_project.yml
- packages.yml
- add elementary package to queries-basedosdados project
- disables materialization for unused  elementary tables
- ideally, all metadata from production tests/runs should be saved in the elementary dataset, but it includes an option to disable data materialization in the `Executa DBT model` pipeline. basedosdados/pipelines/pull/665
> [feat]: add elementary package

- models/br_ms_cnes/br_ms_cnes__estabelecimento.sql
- models/br_ms_cnes/br_ms_cnes__estabelecimento_filantropico.sql
> [fix] br_ms_cnes

- models/br_inep_censo_escolar/br_inep_censo_escolar__escola.sql
- models/br_inep_censo_escolar/schema.yml
fix: adiciona .sql vazio para tabela auxiliar escola_2023
> [fix] br_inep_censo_escolar__escola

- dbt_project.yml
- models/br_cnj_improbidade_administrativa/condenacao.sql
- models/br_cnj_improbidade_administrativa/schema.yml
Algumas coisas para definir:
- Essa tabela não tem uma coluna com qualquer data
- Vai ser BD Pro?
> [dbt]: `br_cnj_improbidade_administrativa.condenacao`

- .github/workflows/cd.yaml
O module `gql` não é encontrado pq o script ta sendo executado fora da env.
[Action](https://github.com/basedosdados/queries-basedosdados/actions/runs/8101345834/job/22141575977#step:7:26)
Continuação de #440 e #471
Espero que isso finalmente resolva
> run script `change_metadata_status.py` in env

- dbt_project.yml
- models/br_cvm_fi/schema.yml
closes #505 
Pequeno pr para corrigir o teste da tabela `documentos_balancete`
Resultado do teste corrigido em `dev`:
```bash
20:33:07  Running with dbt=1.5.6
20:33:10  Registered adapter: bigquery=1.5.6
20:33:12  Found 438 models, 1412 tests, 0 snapshots, 0 analyses, 1164 macros, 2 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
20:33:12
20:33:34
20:33:34  Running 1 on-run-start hook
20:33:35  1 of 1 START hook: elementary.on-run-start.0 ................................... [RUN]
20:33:35  1 of 1 OK hook: elementary.on-run-start.0 ...................................... [OK in 0.00s]
20:33:35
20:33:35  Concurrency: 2 threads (target='dev')
20:33:35
20:33:35  1 of 1 START test dbt_utils_unique_combination_of_columns_documentos_balancete_data_competencia__plano_contabil_ …
```
> [fix]: fix `documentos_balancete` test

- models/br_ibge_ipca/br_ibge_ipca__mes_brasil.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_brasil.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_municipio.sql
- models/br_ibge_ipca/br_ibge_ipca__mes_categoria_rm.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_brasil.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_brasil.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_municipio.sql
- models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_rm.sql
Faz fix temporário de valores duplicados em br_ibge_ipca e br_ibge_ipca15
`1. br_ibge_ipca`
- mes_brasil - 2023 10 & 2024 2 duplicados
- mes_categoria_brasil - 2023 10
- mes_categoria_municipio - 2023 10
- mes_categoria_rm - 2023 10
`2. br_ibge_ipca15`
- mes_brasil - sem duplicatas (por precaução retirei)
- mes_categoria_brasil - 2023 10
- mes_categoria_municipio - 2023 10
- mes_categoria_rm - 2023 10
> [fix] br_ibge_

- dbt_project.yml
- models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
- models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
- models/br_ibge_pam/code/api_to_json.py
- models/br_ibge_pam/code/json_to_parquet.py
- models/br_ibge_pam/schema.yml
> add: br_ibge_pam models + code

- models/br_cgu_beneficios_cidadao/schema.yml
- Remove os testes de chave única composta do conjunto `br_cgu_beneficios_cidadao`. Os beneficiários menores de idade possuem o mesmo nome e não possuem o NIS, quebrando o teste.
query:
```sql
with validation_errors as (
select
nome_favorecido, ano_competencia, mes_competencia, ano_referencia, mes_referencia, id_municipio, nis_favorecido, valor_parcela
from `basedosdados-dev`.`br_cgu_beneficios_cidadao`.`novo_bolsa_familia`
group by nome_favorecido, ano_competencia, mes_competencia, ano_referencia, mes_referencia, id_municipio, nis_favorecido, valor_parcela
having count(*) > 1
)
select *
from validation_errors
```
Resultado:
> [fix]: rm unique_combination_columns tests

- macros/custom_get_where_subquery.sql
- models/br_bcb_estban/schema.yml
- models/br_ibge_pam/schema.yml
- models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
- models/br_ms_sia/br_ms_sia__psicossocial.sql
- models/br_ms_sia/schema.yml
- models/mundo_transfermarkt_competicoes/schema.yml
- models/mundo_transfermarkt_competicoes_internacionais/schema.yml
1. Adiciona testes incrementais nas tabelas dos conjuntos `br_ms_sia` e `br_bcb_estban`
2. Adiciona macro `custo_get_where_subquery`
> [dbt] add macro and modify tests

- .github/workflows/check-bq-project-name.yml
- .github/workflows/scripts/check_sql_files.py
- models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql
- models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__sistema_harmonizado.sql
- models/br_bd_diretorios_mundo/download_sh4_ncm.ipynb
- models/br_bd_diretorios_mundo/schema.yml
1. Adiciona novos diretórios em `br_bd_diretorios_mundo`
- Sistema Harmonizado
- Nomenclatura comum do mercosul
2. Corrige action `check_sql_files`
- A Action buscava por arquivos modificados e procura dados deles. Caso o arquivo seja deletado, trigga a modificação porém o arquivo não existe o que acabava crashando a action. Adicionei um check p/ verificar se o arquivo existe no início da action
[log](https://github.com/basedosdados/queries-basedosdados-dev/actions/runs/8752789199) da run da action com erro
> [dbt] novos diretórios

- models/mundo_transfermarkt_competicoes/mundo_transfermarkt_competicoes__brasileirao_serie_a.sql
corrige colunas `valor_equipe_mandante, valor_equipe_visitante, idade_media_mandante e idade_media_visitante`
> [fix]: `brasileirao_serie_a` model

- models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__faixa_etaria.sql
- models/br_inep_sinopse_estatistica_educacao_basica/code/main.py
Para `11_a_14_anos` o valor é 6
> [dbt]: fix `br_inep_sinopse_estatistica_educacao_basica.faixa_etaria`

- dbt_project.yml
- models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cbo_2002.sql
- models/br_bd_diretorios_brasil/schema.yml
- models/br_ms_sih/br_ms_sih__servicos_profissionais.sql
- models/br_ms_sih/schema.yml
- adiciona query e testes para a tabela `br_ms_sih.servicos_profissionais`
- adiciona novos dados no diretório de cbo_2002
> [dbt]: add `br_ms_sih` models

- macros/custom_get_where_subquery.sql
- tests/generic/custom_dictionaries.sql
- tests/generic/custom_relationships.sql
- tests/generic/custom_unique_combination_of_columns.sql
closes #545 
**1. Adiciona novos testes customizados**
- `custom_relationships`: permite settar valores que podem ser ignorados manualmente ou informar uma proporção de erros tolerável.
- `custom_unique_combinations_of_columns`: permite  settar uma proporção de erros tolerável.
**2. Adiciona documentação dos testes customizados na Wiki**
- ver [link](https://github.com/basedosdados/pipelines/wiki/Testar-modelos-dbt-localmente#testes-customizados)
**3. Adiciona documentação do config where na wiki**
**4. Adiciona explicação do uso  da macro custom_get_where_subquery  com config where na wiki para fazer testes incrementais**
- ver [link](https://github.com/basedosdados/pipelines/wiki/Testar-modelos-dbt-localmente#uso-do-where-com-a-macro-customizada-custom_get_where_subquery-localizada-em-mo …
> [dbt] add custom tests

- dbt_project.yml
- models/br_ibge_ppm/br_ibge_ppm__efetivo_rebanhos.sql
- models/br_ibge_ppm/br_ibge_ppm__producao_aquicultura.sql
- models/br_ibge_ppm/br_ibge_ppm__producao_origem_animal.sql
- models/br_ibge_ppm/br_ibge_ppm__producao_pecuaria.sql
- models/br_ibge_ppm/efetivo_rebanhos/code/api_to_json.py
- models/br_ibge_ppm/efetivo_rebanhos/code/json_to_parquet.py
- models/br_ibge_ppm/producao_aquicultura/code/api_to_json.py
- models/br_ibge_ppm/producao_aquicultura/code/json_to_parquet.py
- models/br_ibge_ppm/producao_origem_animal/code/api_to_json.py
- models/br_ibge_ppm/producao_origem_animal/code/json_to_parquet.py
- models/br_ibge_ppm/producao_pecuaria/code/join_parquet.py
- models/br_ibge_ppm/producao_pecuaria/source/ovinos_tosquiados/code/api_to_json.py
- models/br_ibge_ppm/producao_pecuaria/source/ovinos_tosquiados/code/json_to_parquet.py
- models/br_ibge_ppm/producao_pecuaria/source/vacas_ordenhadas/code/api_to_json.py
- models/br_ibge_ppm/producao_pecuaria/source/vacas_ordenhadas/code/json_to_parquet.py
- models/br_ibge_ppm/schema.yml
- models/br_ms_sih/schema.yml
Dados, modelos e arquivos de download/tratamento das tabelas do dataset br_ibge_ppm.
> add: br_ibge_ppm models and files

- models/br_ibge_censo_2022/br_ibge_censo_2022__indigenas_indice_envelhecimento_localizacao_domicilio_municipio.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__indigenas_indice_envelhecimento_terras_indigenas.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__indigenas_localizacao_docimicilio_grupo_idade_municipio.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__indigenas_populacao_residente_grupo_idade_terras_indigenas.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__quilombolas_indice_envelhecimento_localizacao_domicilio_municipio.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__quilombolas_indice_envelhecimento_territorio_quilombola.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__quilombolas_localizacao_domicilio_grupo_idade_municipio.sql
- models/br_ibge_censo_2022/br_ibge_censo_2022__quilombolas_populacao_residente_grupo_idade_territorio_quilombola.sql
- models/br_ibge_censo_2022/schema.yml
> [feat]: add new `br_ibge_censo_2022` models

- models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cbo_1994.sql
- models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cbo_2002.sql
- models/br_bd_diretorios_brasil/schema.yml
- models/br_ibge_censo_2022/schema.yml
- models/br_ms_cnes/br_ms_cnes__dicionario.sql
- `Leva novo dicionário do CNES p/ prod;`
------------------------
`- Insere códigos cbo_2002 atualmente desativados para permitir o cruzamento com a tabela `profissional ` do conjunto `br_ms_cnes``
`- Insere coluna indicador_cbo_2002_ativa que indetifica se o código de 6 dígitos da cbo_2002 permanece ativo ou não
`
Contexto:
- Existem 394 valores distribuidos por 100 milhões de linham que não tem conexão com diretório de CBO. 
1. CBO na tabela de definição do CNES: 223109 é um dos valores que falham no teste. 
2. CBO no diretório da BD: Na BD só esta presente o valor atual;
3. CBO no site do MTE: indica que  a família antiga foi desativada;
> [dbt] br_bd_diretorios_brasil & br_ms_cnes

- models/br_ibge_censo_2022/schema.yml
- models/br_ms_cnes/br_ms_cnes__dados_complementares.sql
- models/br_ms_cnes/br_ms_cnes__dicionario.sql
- models/br_ms_cnes/br_ms_cnes__equipamento.sql
- models/br_ms_cnes/br_ms_cnes__equipe.sql
- models/br_ms_cnes/br_ms_cnes__estabelecimento.sql
- models/br_ms_cnes/br_ms_cnes__estabelecimento_ensino.sql
- models/br_ms_cnes/br_ms_cnes__estabelecimento_filantropico.sql
- models/br_ms_cnes/br_ms_cnes__gestao_metas.sql
- models/br_ms_cnes/br_ms_cnes__habilitacao.sql
- models/br_ms_cnes/br_ms_cnes__incentivos.sql
- models/br_ms_cnes/br_ms_cnes__leito.sql
- models/br_ms_cnes/br_ms_cnes__profissional.sql
- models/br_ms_cnes/br_ms_cnes__regra_contratual.sql
- models/br_ms_cnes/br_ms_cnes__servico_especializado.sql
- models/br_ms_cnes/schema.yml
- tests/generic/custom_dictionary_coverage.sql
- tests/generic/custom_relationships.sql
> [dbt] br_ms_cnes

- models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cid_10.sql
- models/br_bd_diretorios_brasil/schema.yml
- models/br_ms_sih/br_ms_sih__aihs_reduzidas.sql
- models/br_ms_sih/schema.yml
- sobe `br_ms_sih.aihs_reduzidas`
- atualiza `br_bd_diretorios.cid_10`
> [feat]: `br_ms_sih.aihs_reduzidas`

- models/br_me_comex_stat/br_me_comex_stat__dicionario.sql
- models/br_me_comex_stat/schema.yml
- Corrige valores de id_urf e id_pais no dicionário do conjunto br_me_comex_stat
- Insere where config nos testes de br_me_comex_stat
> [fix] br_me_comex_stat

- models/br_tse_eleicoes/br_tse_eleicoes__resultados_candidato.sql
- models/br_tse_eleicoes/br_tse_eleicoes__resultados_candidato_municipio.sql
- models/br_tse_eleicoes/br_tse_eleicoes__resultados_candidato_municipio_zona.sql
- models/br_tse_eleicoes/br_tse_eleicoes__resultados_partido_municipio.sql
- models/br_tse_eleicoes/br_tse_eleicoes__resultados_partido_municipio_zona.sql
Para algumas tabelas estava `tipo_eleicao = eleicoes municipais de 2004 - 1º turno`.
> fix: tipo_eleicao in 2004

- models/br_rf_cno/br_rf_cno__microdados.sql
- models/br_rf_cno/br_rf_cno__vinculos.sql
- Remove pre hook dos modelos vinculos e microdados
- Como as tabelas ainda não estão materializadas o pre hook crasha.
> [fix] br_rf_cno

- models/br_tse_eleicoes/br_tse_eleicoes__despesas_candidato.sql
- models/br_tse_eleicoes/br_tse_eleicoes__receitas_candidato.sql
- models/br_tse_eleicoes/schema.yml
*Atualizando dataset br_tse_eleicoes, tabelas despesas_candidato e receitas_candidato com o ano de 2024*
Tabela|Linhas|Materialização |sources|
|:-:|:-:|:-:|:-:|
receitas_candidato|13401642|862.4 MiB|[:link:][source]
despesas_candidato|28226542|12.45 GB|[:link:][source]
```sql
SELECT * FROM `basedosdados.br_tse_eleicoes.despesas_candidato` where esfera_partidaria_fornecedor is not null
```
```sql
select distinct data_despesa
from `basedosdados`.`br_tse_eleicoes`.`despesas_candidato`
where data_despesa >= current_date()
``` 
```sql
select distinct sigla_uf_doador as from_field
from `basedosdados`.`br_tse_eleicoes`.`receitas_candidato`
where sigla_uf_doador is not null
```
[source]: https://dadosabertos.tse.jus.br/dataset/prestacao-de-contas-eleitorais-2024/resource/c74840a4-f303-4771-af44-e …
> [dados] br_tse_eleicoes: despesas_candidato|receitas_candidato

- models/br_bcb_sicor/br_bcb_sicor__microdados_liberacao.sql
- Corrige nomeação de variáveis da tabela br_bcb_sicor
- erro reportado pelo usuário
> Oi, Gabriel. Claro!  Estou trabalhando com essa tabela: https://basedosdados.org/dataset/544c9d22-97b7-479a-8eca-94762840b465?table=d8514322-a6d4-4c7e-a4f7-3ec7860510f6 e identifiquei que a variavel id_referencia_bacen que deveria ser o identificador unico da tabela está com os valores incorretos.
> [fix] br_bcb_sicor.liberacao

- models/br_ms_sih/br_ms_sih__aihs_reduzidas.sql
- models/br_ms_sih/schema.yml
Neste PR corrigo a tipagem de colunas, retiro zeros a esquerda para padronizar valores de campo com o dicionário e renomeio uma coluna.
> [fix] br_ms_sih.aihs_reduzidas

- models/br_jota/br_jota__eleicao_perfil_candidato_2024.sql
- models/br_jota/br_jota__eleicao_prestacao_contas_candidato_2024.sql
- models/br_jota/br_jota__eleicao_prestacao_contas_candidato_origem_2024.sql
- models/br_jota/br_jota__eleicao_prestacao_contas_partido_2024.sql
- models/br_jota/schema.yaml
*Adicionar modelos para br_jota 2024"
Tabela|Linhas|Materialização |Referencia|
|:-:|:-:|:-:|:-:|
eleicao_perfil_candidato_2024|462157| 41.4 MB|[:link:][source]
eleicao_prestacao_contas_candidato_2024|461858| 74.46 MB|[:link:][source]
eleicao_prestacao_contas_candidato_origem_2024|388234|61.49 MB|[:link:][source]
eleicao_prestacao_contas_partido_2024|287046|28.03 MB|[:link:][source]
[source]: https://www.sigaodinheiro.org/
> [dados]br_jota 2024

- dbt_project.yml
- models/br_sfb_sicar/br_sfb_sicar__area_imovel.sql
- models/br_sfb_sicar/br_sfb_sicar__dicionario.sql
- models/br_sfb_sicar/schema.yml
- Este PR adiciona os modelos dbt e schema yml do conjunto br_sf_sicar
> br_sfb_sicar

- dbt_project.yml
- macros/validate_date_range.sql
- models/br_tse_filiacao_partidaria/br_tse_filiacao_partidaria__microdados_antigos.sql
- models/br_tse_filiacao_partidaria/schema.yml
- tests/generic/custom_null_proportion_multiple_columns.sql
- Adicionar `br_tse_filiacao_partidaria__microdados_antigos` renomeação do atual `microdados` em prod 
- Adicionar `custom_not_null_proportion_multiple_columns` #783
- Adicionar Macro `validate_date_range`
Tabela|Linhas|Materialização|
|:-:|:-:|:-:|
microdados_antigos|24666625| 2.67 GB|
Teste: `relationships` Diretorio Alvo: `br_bd_diretorios_brasil.municipio`
Situação: Temos 130 ids que não se relacionam com o nosso diretorio. Todos eles aparecem como ids referente alguma localização estranhageira.
Solução: Remoção do teste enquanto não for insertido os ids faltantes.
Query:
```sql
with child as (
select id_municipio_tse as from_field
from `basedosdados-dev`.`br_tse_filiacao_partidaria`.`microdados_antigos`
where id_municipio_tse is not null
),
parent as (
select id_municipio_tse as …
```
> [dbt]br_tse_filiacao_partidaria__microdados_antigos, novo custom_test e macro

- models/br_tse_filiacao_partidaria/br_tse_filiacao_partidaria__microdados.sql
- models/br_tse_filiacao_partidaria/schema.yml
- Adicionar `br_tse_filiacao_partidaria__microdados` e seus testes
Tabela|Linhas|Materialização|Arquitetura
|:-:|:-:|:-:|:-:|
microdados|17173906| 3.4 GiB|[🔗 ][arquitetura]
Teste: `relationships` Diretorio Alvo: `br_bd_diretorios_brasil.municipio`
Situação: Temos 130 ids que não se relacionam com o nosso diretorio. Todos eles aparecem como ids referente alguma localização estranhageira.
Solução: Remoção do teste enquanto não for insertido os ids faltantes.
Teste: `custom_relationships` Diretorio Alvo: `br_bd_diretorios_brasil.uf`
Situação: Sigla 'ZZ' não se encontra no diretorio.
Solução: Colocar 'ZZ' dentro dos valores a serém ignorados dentro do teste
Coluna `data_exclusao, nome_social, data_cancelamento, motivo_cancelamento, data_cadastro_desfiliacao` e outras tem menos de 1% de …
> [dados]br_tse_filiacao_partidaria.microdados

- models/br_ibge_censo_2022/br_ibge_censo_2022__municipio.sql
Mudei as colunas da tabela de alfabetização após já ter materializado e testado a tabela de municipio. 
Com a mudança o modelo quebrou
Subindo alterações no modelo dbt para materializar a tabela de municipio
> fix: br_ibge_censo_2022.municipio

- tests/generic/custom_dictionary_coverage.sql
Este PR refatora o teste custom_dictionary_coverage que não reconhecia o table_id da objeto model do DBT e compilava o teste tem o table_id da tabela a ser testada.
ver #826 
teste feito nas tabelas br_e_comex_stat.ncm_exportacao & br_rf_cno.vinculos
> [Refactor] custom_dicionary_coverage

- models/br_sfb_sicar/br_sfb_sicar__area_imovel.sql
- Modifica a forma de criar coluna **id_municipio** na tabela **area_imovel**
- Anteriormente, o id_municipio era criado cruzando nomes de município com o diretório. O código do car, id_car, possui o id_municipio como componente. A novo modelo extrai id_municipio diretamente do id_car
> [Refactor] br_sfb_sicar

- models/br_tse_eleicoes/br_tse_eleicoes__detalhes_votacao_municipio.sql
- models/br_tse_eleicoes/br_tse_eleicoes__detalhes_votacao_municipio_zona.sql
- models/br_tse_eleicoes/br_tse_eleicoes__detalhes_votacao_secao.sql
- models/br_tse_eleicoes/br_tse_eleicoes__partidos.sql
- models/br_tse_eleicoes/br_tse_eleicoes__perfil_eleitorado_local_votacao.sql
- models/br_tse_eleicoes/br_tse_eleicoes__perfil_eleitorado_municipio_zona.sql
- models/br_tse_eleicoes/br_tse_eleicoes__perfil_eleitorado_secao.sql
- models/br_tse_eleicoes/br_tse_eleicoes__vagas.sql
- models/br_tse_eleicoes/schema.yml
Esse PR finaliza as ultimas tabelas  do conjunto `br_tse_eleicoes` com dados disponíveis de 2024 para serem atualizados.
> [dbt]br_tse_eleicoes - Atualizar dados 2024 TSE

- .github/workflows/cd.yaml
- .github/workflows/ci-dbt.yaml
- .github/workflows/docs.yaml
- .github/workflows/sync-dbt-schema.yaml
- .github/workflows/test_dbt_model.yaml
- .github/workflows/triggers-elementary-model.yaml
Estamos temporariamente fixando a versão do poetry para 1.8.5, porque a versão 2.0.0 está quebrando nosso [teste][test].
Isso é apenas para não travar a fila de PR, enquanto buscamos uma solução mais completa.
[test]: https://github.com/basedosdados/queries-basedosdados/actions/runs/12653167251/job/35257721570
> [fix]Fixando versão do poetry temporariamente

- .github/workflows/cd.yaml
Infelizmente mais alterações serão necessarias para consegui rodar `cd.yaml` com: 
```yaml
on:
push:
branches: [main]
```
Vamos retorna para a versão antiga e desativar a função atualmente quebrada do `change-metadata-status`
> [Refactor]Retornando cd.yaml para 'on pull_request e desativando 'change-metada'

- .github/workflows/elementary.yaml
> [!WARNING]
> actions/upload-artifact@v3 is scheduled for deprecation on **November 30, 2024**. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
> Similarly, v1/v2 are scheduled for deprecation on **June 30, 2024**.
> Please update your workflow to use v4 of the artifact actions.
> This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
> [Fix] Atualizar upload-artifact em elementary.yml

- models/br_inpe_queimadas/br_inpe_queimadas__microdados.sql
- models/br_inpe_queimadas/schema.yaml
[Fix]Remoção de colunas excessivas - br_inpe_queimadas__microdados
Algumas colunas excessivas estão sendo removidas para uma melhor leitura e utilização dos dados
Colunas removidas:
- dia
- hora
- minuto
- segundo
> [Fix]Remoção de colunas excessivas - br_inpe_queimadas__microdados

- tests/generic/not_null_proportion_multiple_columns.sql
- `Preenchimento` não deixava claro que estamos falando da proporção de linhas vazias na tabela
- `Preenchimento ideal` não traz nenhuma informação nova. Apenas enfatiza o valor colocado em `at_least`
- ` Proporção Null` indica melhor que a o numero é referente a proporção de linhas vazias na tabela
- `'at_least' Recomendado` agora indica o valor que `at_least` precisa ter para que o test tenha sucesso nessa coluna
- `Qualidade` renomeado para `Qualidade Null`
- Caso a coluna esteja totalmente vazia. Um aviso vai ser destacado,
- Foi colocado cor para realçar a recomendação de `'at_least' Recomendado`
- Cor vermelha no texto `FAIL` para deixa claro que apesar da cor amarela da recomendação, essa coluna falhou no teste
> [Refactor]Modificando log not_null_proportion_multiple_columns

- models/br_cgu_servidores_executivo_federal/br_cgu_servidores_executivo_federal__remuneracao.sql
- Um usuário relatou um erro na tabela de remuneração. Apenas removi os .0 do id_servidor para resolver essa questão.
Mensagem do usuário:
Mensagem do usuário:
Olá pessoal, 
fiz uma query para puxar os dados dos servidores puxando a tabela "reumuneração"  e "cadastro servidores". Fiz a consulta para ano = 2023,  mes = 12. Ao tentar fazer um join utilizando a variável id_servidor, identifiquei que os dados da tabela "remuneração" estão com digitos a mais, terminando em ".0". Não verifiquei outros anos e meses. Acredito que pelo tratamento da BD essas variáveis deveriam estar harmonizadas, correto? Obrigado. Raphael
> [bug] br_cgu_servidores_executivo_federal.remuneracao

- models/br_me_rais/br_me_rais__dicionario.sql
- models/br_me_rais/br_me_rais__microdados_vinculos.sql
- Um usuário relatou um bug na coluna `sexo`. Segue o link: https://discord.com/channels/787841210433536010/1368012920356868147/1368012920356868147
Testes completos em dev:
> [BugFix] br_me_rais
