basedosdados/queries-basedosdados

models/br_me_comex_stat/dicionario.sql, models/br_me_comex_stat/ncm_importacao.sql, models/br_me_comex_stat/schema.yml
fix dbt model for br_me_comex_stat.ncm_importacao
=> [dbt] br_me_comex_stat

models/br_ons_avaliacao_operacao/schema.yml
=> [dbt] br_ons_avaliacao_operacao

models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__empresa.sql
undo post-hook br_bd_diretorios_brasil__empresa.sql
=> [dbt] br_bd_diretorios_brasil__empresa

models/br_me_comex_stat/ncm_importacao_atualizado.sql
fix ncm_importacao_atualizado dbt model
=> br_me_comex_stat

models/br_ms_cnes/br_ms_cnes__dicionario.sql
fix br_ms_cnes.dicionario column name
=> br_ms_cnes

dbt_project.yml
=> [bdpro] br_bcb_taxas

models/br_ans_beneficiario/informacao_consolidada.sql
=> [dbt] grant br_ans_beneficiario

models/br_ms_cnes/leito.sql, models/br_ms_cnes/profissional.sql
- Adiciona dbt sem pre-hook para criar as tabelas
=> [dbt] br_ms_cnes

dbt_project.yml, models/br_rf_cafir/br_rf_cafir__dicionario.sql, models/br_rf_cafir/br_rf_cafir__imoveis_rurais.sql, models/br_rf_cafir/schema.yml
Adiciona modelos dbt e schemas do br_rf_cafir
=> [dbt] `br_rf_cafir`

dbt_project.yml, models/br_bcb_sicor/br_bcb_sicor__dicionario.sql, models/br_bcb_sicor/br_bcb_sicor__empreendimento.sql, models/br_bcb_sicor/br_bcb_sicor__microdados_liberacao.sql, models/br_bcb_sicor/br_bcb_sicor__microdados_operacao.sql, models/br_bcb_sicor/br_bcb_sicor__microdados_saldo.sql, models/br_bcb_sicor/br_bcb_sicor__recurso_publico_complemento_operacao.sql, models/br_bcb_sicor/br_bcb_sicor__recurso_publico_cooperado.sql, models/br_bcb_sicor/br_bcb_sicor__recurso_publico_gleba.sql, models/br_bcb_sicor/br_bcb_sicor__recurso_publico_mutuario.sql, models/br_bcb_sicor/br_bcb_sicor__recurso_publico_propriedade.sql, models/br_bcb_sicor/schema.yml
- Adiciona schema e modelos dbt de br_bcb_sicor
#295
=> [dbt] `br_bcb_sicor`

models/br_me_caged/microdados_movimentacao.sql, models/br_me_caged/microdados_movimentacao_excluida.sql, models/br_me_caged/microdados_movimentacao_fora_prazo.sql
subindo o mês 8 do br_me_caged e mudando a sintaxe do grant.
=> [dbt] br_me_caged upload

models/br_ms_cnes/profissional.sql
- Leva dados do Storage de dev para Storage de prod e materializa tabela para inserir dados de 2015.
=> [dbt] br_ms_cnes.profissional

models/br_ms_cnes/profissional.sql
- Retira materialização incremental para 're-materializar' a tabela de profissional do cnes e adicionar o ano de 2015.
=> [fix] br_ms_cnes

models/br_fbsp_absp/br_fbsp_absp__uf.sql, models/br_fbsp_absp/schema.yaml
PR referente à issue #199 
PR para acionar o Action. 🤞
=> [dados] br_fbsp_absp

.github/workflows/deploy.yaml, .github/workflows/docs.yaml, .github/workflows/sync-dbt-schema.yaml, README.md
1. Atualizar branch principal para main
2. Mergear o PR
=> feat: migrate branch to main

models/world_oceanos_mapeamento/schema.yaml
- Insere descrição da tabela   `world_oceanos_mapeamento__mapeamento` no  `schema.yml`
=> conserta schema oceanos

models/br_me_caged/microdados_movimentacao.sql, models/br_me_caged/microdados_movimentacao_excluida.sql, models/br_me_caged/microdados_movimentacao_fora_prazo.sql
closes #306 
sobe mês 09 do caged
=> [dados-atualizacao] br_me_caged

dbt_project.yml, models/br_inpe_queimadas/br_inpe_queimadas__microdados.sql, models/br_inpe_queimadas/code/[dados]_br_inpe_queimadas.ipynb, models/br_inpe_queimadas/schema.yaml
Sobe dados de focos de queimadas
=> [dados] br_inpe_queimadas

models/br_me_cnpj/estabelecimentos.sql
=> [fix] br_me_cnpj.estabelecimentos

dbt_project.yml, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__bpc.sql, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__garantia_safra.sql, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__novo_bolsa_familia.sql, models/br_cgu_beneficios_cidadao/schema.yml
Modelos para o dataset `br_cgu_beneficios_cidadao`
=> [dbt] `br_cgu_beneficios_cidadao`

models/br_ans_beneficiario/informacao_consolidada.sql, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__bpc.sql, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__garantia_safra.sql, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__novo_bolsa_familia.sql
=> feat: adding pre-hook on br_cgu_beneficios_cidadao and br_ans_beneficiario

models/br_bcb_agencia/br_bcb_agencia__agencia.sql, models/br_bcb_estban/br_bcb_estban__agencia.sql, models/br_bcb_estban/br_bcb_estban__municipio.sql, models/br_me_comex_stat/br_me_comex_stat__dicionario.sql, models/br_me_comex_stat/br_me_comex_stat__municipio_exportacao.sql, models/br_me_comex_stat/br_me_comex_stat__municipio_importacao.sql, models/br_me_comex_stat/br_me_comex_stat__ncm_exportacao.sql, models/br_me_comex_stat/br_me_comex_stat__ncm_importacao.sql, models/br_me_comex_stat/schema.yml
1.  Adiciona alias nas tabelas:
- `br_bcb_estban`, `br_bcb_agencia` e `br_comex_stat `
2. Insere modelos dbt incrementais em:
- `br_comex_stat `
=> [dbt] fix br_bcb_estban, br_bcb_agencia & br_comex_stat

models/br_trase_supply_chain/br_trase_supply_chain__soy_beans_refining_facilities.sql
- corrige erro de digitação no modelo soy_beans_refining_facilities
=> [dbt] br_trase_supply_chain

models/br_bcb_estban/br_bcb_estban__agencia.sql, models/br_bcb_estban/br_bcb_estban__municipio.sql
- Adiciona dados históricos das tabelas `municipio ` e `agencia ` do conjunto `br_bcb_estban`
- 2023-05 a 2023-09
=> [dbt] br_bcb_estban

models/br_inpe_queimadas/br_inpe_queimadas__microdados.sql, models/br_inpe_sisam/br_inpe_sisam__microdados.sql, models/br_inpe_sisam/code/[dados]_br_inpe_sisam.ipynb, models/br_inpe_sisam/schema.yaml
Add dados de saúde e meio ambiente
Fix partição na tabela de queimadas
=> [dados] br_inpe_sisam

models/br_firjan_ifgf/br_firjan_ifgf__ranking.sql, models/br_firjan_ifgf/code/[dados]_br_firjan_ifgf.ipynb, models/br_firjan_ifgf/schema.yaml
Add dados do Índice Firjan de Gestão Fiscal
=> [dados] br_firjan_ifgf

models/br_denatran_frota/br_denatran_frota__municipio_tipo.sql, models/br_denatran_frota/br_denatran_frota__uf_tipo.sql, models/br_denatran_frota/schema.yml
Insere modelos DBT e schema para br_denatran_frota
=> [dbt] br_denatran_frota

models/br_me_caged/microdados_movimentacao.sql, models/br_me_caged/microdados_movimentacao_excluida.sql, models/br_me_caged/microdados_movimentacao_fora_prazo.sql
=> [dbt] br_me_caged 12/24 update 

.github/workflows/ci-dbt.yaml, .github/workflows/ci-docker.yaml
No meio de toda a confusão faltou adicionar essas actions
=> fix: add lint actions

.github/workflows/ci-dbt.yaml, dbt_project.yml
adiciona opções para desabilitar o elementary via dbt cli
=> [feat]: add options to disable elementary models

models/br_ms_cnes/br_ms_cnes__estabelecimento.sql, models/br_ms_cnes/br_ms_cnes__estabelecimento_filantropico.sql, models/br_ms_cnes/br_ms_cnes__habilitacao.sql
fix: temporary remove pre hook to materialize table
=> [dbt] br_ ms_cnes

models/br_ons_estimativa_custos/br_ons_estimativa_custos__custo_variavel_unitario_usinas_termicas.sql
- remove vírgula depois do parêntese que fecha a declaração do config no modelo dbt.
=> [dbt]br_ons_avaliacao_operacao

models/br_ms_cnes/br_ms_cnes__leito.sql
=> [dbt] br_ms_cnes.leito

models/br_inep_saeb/br_inep_saeb__dicionario.sql, models/br_inep_saeb/schema.yml
Atualização do dicionário do SAEB: inclusão das tabelas aluno_ef_2_ano e aluno_ef_5_ano no dicionário e atualização de chaves e valores que mudaram em 2021
=> [dados-atualização] br_inep_saeb__dicionario

models/br_inep_censo_escolar/br_inep_censo_escolar__escola.sql, models/br_inep_censo_escolar/schema.yml, models/br_inep_saeb/br_inep_saeb__dicionario.sql, models/br_inep_saeb/schema.yml
fix: subido dicionario SAEB e escola Censo de novo
=> [fix] br_inep_saeb__dicionario & br_inep_censo_escolar__escola

models/br_cnj_improbidade_administrativa/br_cnj_improbidade_administrativa__condenacao.sql
Depois de #474 a action deve funcionar.
=> trigger br_cnj_improbidade_administrativa.condenacao

models/br_mp_pep/br_mp_pep__cargos_funcoes.sql, models/br_mp_pep/schema.yml
- Adicionando alias para a tabela
=> [dbt]: br_mp_pep_cargos_funcoes add dbt alias

models/br_me_caged/microdados_movimentacao.sql, models/br_me_caged/microdados_movimentacao_excluida.sql, models/br_me_caged/microdados_movimentacao_fora_prazo.sql
=> [dados-atualizacao]: update caged 01-24

models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__auxilio_brasil.sql
- Atualizando os dados do Auxilio Brasil para os anos de 2021/11 e 2021/12 que o voluntário me mandou posteriormente.
=> [update] update auxilio brasil date 2021/11 and 2021/12

models/br_ms_cnes/br_ms_cnes__estabelecimento.sql
convert bytes to string column tipo_avaliacao_pnass
=> [fix] br_ms_cnes.estabelecimento

models/br_camara_dados_abertos/br_camara_dados_abertos__orgao_deputado.sql, models/br_camara_dados_abertos/br_camara_dados_abertos__proposicao_microdados.sql
- `proposicao_microdados`: Fiz uma query para anular as datas que são maiores que a data atual e assim o update metadata ficar certo após a atualização.
- `orgao_deputado`: Retirando uma linha que quebrava o teste
=> [fix] br_camara_dados_abertos.proposicao_microdados

models/br_anatel_banda_larga_fixa/schema.yml, models/br_anatel_telefonia_movel/schema.yml
* Adiciono os testes nas pipelines da anatel
* **Ps: Não há teste de nível de observação nas tabelas de microdados.**
=> [dbt] add dbt test anatel

models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql, models/br_ms_sia/br_ms_sia__psicossocial.sql
`1. Psicossocial
`- Corrige typo
- Setta modelo incremental
`2. Produção Ambulatorial`
- cria nova CTE para padronizar tipos de dados entre tabela materializada e tabela sendo materializada
=> [dbt] br_ms_sia

models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
- Corrige erro de ambiguidade na lógica de materilização incremental
=> [fix] br_ms_sia

models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
- Adiciona nova lógica incremental para tabela producao_ambolutarial sem usar joins
=> [fix-sia] producao_ambulatorial

models/mundo_transfermarkt_competicoes/schema.yml, models/mundo_transfermarkt_competicoes_internacionais/schema.yml
https://github.com/basedosdados/pipelines/issues/725
=> [feat]: add tests to `transfermarkt_competicoes` models

.github/workflows/check-bq-project-name.yml, .github/workflows/scripts/check_sql_files.py, models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__novo_bolsa_familia.sql
Verifica a existencia do projeto `basedosdados-dev` dentro dos arquivos .sql presentes no PR.
=> [feat]: add action to check bq project name

models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql, models/br_bd_diretorios_mundo/schema.yml
1. Reordena colunas;
2. Modifica descrição;
3. Insere nova coluna;
=> fix: nomenclatura_comum_mercosul

.pre-commit-config.yaml
Mesma alteração em https://github.com/basedosdados/queries-basedosdados-dev/pull/491
=> pre-commit yamlfix: exclude folders

dbt_project.yml, models/br_inep_ideb/br_inep_ideb__escola.sql, models/br_inep_ideb/br_inep_ideb__municipio.sql, models/br_inep_ideb/code/main.py, models/br_inep_ideb/schema.yml
https://github.com/orgs/basedosdados/projects/17/views/13?filterQuery=&pane=issue&itemId=59212377
=> [dbt]: add br_inep_ideb

models/br_cvm_fi/schema.yml, models/br_ms_sih/br_ms_sih__dicionario.sql, models/br_ms_sih/schema.yml
=> [fix]: br_cvm_fi tests

models/br_camara_dados_abertos/schema.yml
- Acrescentando os testes personalizados
- Substituindo `not_null_proportion` por `not_null_proportion_multiple_columns`
=> fix test dbt in table the camara

dbt_project.yml, models/br_ipea_avs/br_ipea_avs__municipio.sql, models/br_ipea_avs/schema.yml
- Consertando a tabela da AVS.
- Adicionando a coluna udh.
- Adicionando os testes.
=> [br_ipea-avs] fix avs and add tests

models/br_ms_cnes/br_ms_cnes__estabelecimento_filantropico.sql
- Conserta typo no config do modelo br_ms_cnes.estabelecimento_filantropico
=> [fix] br_ms_cnes.estabelecimento_filantropico

.github/workflows/ci-dbt.yaml, models/br_ms_sih/schema.yml
Trazendo a mudança de https://github.com/basedosdados/queries-basedosdados-dev/pull/557
=> Update ci dbt event and fix `yamlfix` command

models/br_ms_sih/br_ms_sih__aihs_reduzidas.sql, models/br_ms_sih/br_ms_sih__servicos_profissionais.sql
`- Adiciona pre hook nos modelos DBT do conjunto br_ms_sih`
- [Flow](https://prefect.basedosdados.org/default/task-run/e98da433-ca44-47e4-a4f3-2273630fa5cd?logs) com erro
- Erro
```py
Exception: Error running sync command: Database Error in model br_ms_sih__aihs_reduzidas (models/br_ms_sih/br_ms_sih__aihs_reduzidas.sql)
User does not have full access for table 'basedosdados.br_ms_sih.aihs_reduzidas' due to row access policies.
compiled Code at target/run/basedosdados/models/br_ms_sih/br_ms_sih__aihs_reduzidas.sql
```
=> [fix] br_ms_sih

models/br_ans_beneficiario/informacao_consolidada.sql
=> [fix] br_ans_beneficiarios.informacao_consolidada

models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cnae_2.sql, models/br_bd_diretorios_brasil/code/cnae_2.py, models/br_bd_diretorios_brasil/schema.yml
- Atualiza diretório da cnae_2
=> [dados] br_bd_diretorios_brasil.cnae_2

models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__instituicao_ensino_superior.sql, models/br_bd_diretorios_brasil/code/[update]instituicao_ensino_superior.ipynb, models/br_inep_censo_escolar/schema.yml
*Atualizando dataset br_bd_diretorios_brasil e preparando diretorio para #426*
Categoria|Linhas|
|:-:|:-:|
Pre-update|5706|
Pos-update|6589|
Acréscimo|833|
**Atualização foi realizada com a utilização do [Censo da Educação Superior][ies].**
[ies]: https://basedosdados.org/dataset/a3b57cca-ff80-4bf2-8bac-c145109e06a7?table=e8ee3373-0f3d-4617-849c-c730970a819e
[initcap]: https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#initcap
[diretorio]: https://basedosdados.org/dataset/33b49786-fb5f-496f-bb7c-9811c985af8e?table=9c8ed04c-d617-4b5b-9e0c-ea4f9a945f04
=> [dados]br_bd_diretorios_brasil.instituicao_ensino_superior

models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__etapa_ensino_serie.sql
fix modelo dbt sinopse_estatistica_educacao_basica__etapa_ensino_serie
=> [dbt] sinopse_estatistica_educacao_basica__etapa_ensino_serie

models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__faixa_etaria.sql
subindo novos dados da tabela faixa_etaria no storage, mesmo modelo dbt
=> [dbt] br_inep_sinopse_estatistica_educacao_basica__faixa_etaria

models/br_me_comex_stat/schema.yml, models/br_me_siconfi/br_me_siconfi__municipio_despesas_funcao.sql
- Retira testes not_null_multiple_columns do conjunto  br_me_comex
- Aplica linter no modelo br_me_siconfi.municipio_despesas_funcao
=> [fix] br_me_comex

models/br_mec_sisu/br_mec_sisu__microdados.sql
Alteração no caminho para br_bd_diretorios_brasil.municipio em produção.
=> [Fix]br_mec_sisu

models/br_inep_ideb/br_inep_ideb__brasil.sql, models/br_inep_ideb/schema.yml
=> br_inep_ideb.brasil: fix col rede

models/br_inep_saeb/code/taxa_alfabetizacao_uf_br.py
Código para atualização da taxa de alfabetização divulgado pelo SAEB.
=> br_inep_saeb: add taxa_alfabetizacao_uf_br.py

models/br_inep_ideb/br_inep_ideb__uf.sql, models/br_inep_ideb/code/fix_ideb_uf_2021.py, models/br_inep_ideb/schema.yml
Close #721
Adicionando modelo dbt para tabela porque não existia
=> Correção de `br_inep_ideb.uf` para 2021

models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql
Atualiza diretório nomenclatura_comum_mercosul do conjunto br_bd_diretorios_mundo em produção
=> [fix] br_bd_diretorios_mundo.nomenclatura_comum_mercosul

models/br_inep_saeb/br_inep_saeb__dicionario.sql
Continuação de #709
Apenas levando para prod
=> [dbt]: materialize br_inep_saeb.dicionario

models/br_ms_sih/br_ms_sih__dicionario.sql
Neste PR levo o dicionário de dev atualizado para produção. Atualmente, o dicionário em prod não possui as colunas da tabela aihs_reduzidas.
**Removi as colunas:**
sexo_paciente, raca_cor_paciente, indicador_gestante_risco, indicador_infeccao_hospitalar
**Renomeei a coluna**
indicador_vinculo_previdencia para tipo_vinculo_previdencia
=> [fix] br_ms_sih.dicionario

models/br_jota/br_jota__eleicao_auxiliar_categoria_origem.sql, models/br_jota/schema.yaml
*Adicionar tabela eleicao_auxiliar_categoria_origem*
Tabela|Linhas|Materialização |
|:-:|:-:|:-:|
eleicao_auxiliar_categoria_origem|50| 2.69 KB
=> [dados]br_jota.tabela eleicao_auxiliar_categoria_origem

models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql
Este PR corrige os dados do diretório nomenclatura_comum_mercosul, atualizando os dados brutos em basedosdados-staging.
=> [fix] nomenclatura_comum_mercosul

models/br_tse_eleicoes/schema.yml
**Teste em `sigla_uf_nascimento` foi adicionado teste e agora está sendo consertado [PR](#763 )**
=> [fix] br_tse_eleicoes__candidatos - sigla_uf_nascimento

models/br_inep_censo_educacao_superior/br_inep_censo_educacao_superior__curso.sql, models/br_inep_censo_educacao_superior/br_inep_censo_educacao_superior__ies.sql, models/br_inep_censo_educacao_superior/schema.yml
* Rodando o table-approve nas tabelas de `curso` e `ies`
* Removendo os testes de id_curso e id_ies. Segue as querys abaixo:
1. Acredito que precise atualizar a tabela do nosso diretório de ies.
2. Em relação a id_curso, os valores realmente não batem.
`id_curso na tabela de curso`
```sql
with child as (
select id_curso as from_field
from `basedosdados-dev`.`br_inep_censo_educacao_superior`.`curso`
where id_curso is not null
),
parent as (
select id_curso as to_field
from `basedosdados-dev`.`br_bd_diretorios_brasil`.`curso_superior`
)
select
from_field
from child
left join parent
on child.from_field = parent.to_field
where parent.to_field is null
```
`id_ies na tabela de ies`
```sql
with child as (
select id_ies as from_field
from `basedosdados-dev`.`br_inep_censo_educacao_superior`.`ies` …
```
=> [dbt] br_inep_censo_educacao_superior

models/br_ms_sim/br_ms_sim__dicionario.sql
* Consertando o dicionário da SIM, após a mensagem de um [usuário](https://github.com/orgs/basedosdados/projects/17/views/9?filterQuery=assignee%3Atricktx&pane=issue&itemId=83231941)
=> [fix] br_ms_sim.dicionario

models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_deficiencia.sql, models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_escolaridade.sql, models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_etapa_ensino.sql, models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_faixa_etaria_sexo.sql, models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_localizacao.sql, models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_regime_contrato.sql, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_deficiencia.py, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_escolaridade.py, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_faixa_etaria_sexo.py, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_localizacao.py, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_regime_contratacao.py, models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docentes_etapa_ensino.py, models/br_inep_sinopse_estatistica_educacao_basica/schema.yml
* Subindo os dados de docentes
* Retirando alguns .0 que subiram junto com o código python.
* Subindo o código que rodei manualmente para tratar os dados (Eles são um pouco confuso, as colunas, abas e variáveis mudam muito durante os anos)
=> [dbt] br_inep_sinopse_estatistica_educacao_basica.docente

models/br_me_cnpj/br_me_cnpj__empresas.sql, models/br_me_cnpj/br_me_cnpj__estabelecimentos.sql, models/br_me_cnpj/br_me_cnpj__socios.sql
Este PR modifica a lógica de materialiozação incremetal para materializar novamente as 2 últimas particões das tabelas socios, estabelecimentos e empresas em produção.
=> [BugFix] br_me_cnpj

models/br_rf_arrecadacao/br_rf_arrecadacao__itr.sql, models/br_rf_arrecadacao/schema.yml
Correção na formatação e processamento de colunas da tabela br_rf_arrecadacao.itr
- Coluna sigla_regiao foi removida.
- Coluna id_municipio foi adicionada, a partir de JOIN com tabela do diretório.
- Coluna nome_municipio foi mantida, visando identificação única de cada linha, mesmo em situações onde o id_municipio não foi encontrado.
- [x ]  Testado em `queries-basedosdados-dev`
- [ x] **Decisões relacionadas aos testes: nome_municipio foi utilizado nos testes de unicidade de múltiplas colunas.
- Identifique os riscos potenciais desta mudança e como mitigar esses Riscos
- Riscos conhecidos: 
- Planos de rollback: 
- Liste quaisquer dependências externas, como bibliotecas, outros PRs ou mudanças que precisam ser feitas antes …
=> [fix]br_rf_arrecadacao.itr

models/br_rf_arrecadacao/br_rf_arrecadacao__itr.sql
Correção no caminho para o `basedosdados.br_bd_diretorios_brasil.municipio`
=> [Fix]br_rf_arrecadacao__itr

models/br_tse_eleicoes/br_tse_eleicoes__resultados_candidato_secao.sql, models/br_tse_eleicoes/br_tse_eleicoes__resultados_partido_secao.sql, models/br_tse_eleicoes/schema.yml
Atualização segundo turno e adaptação da falta do `id_candidato_bd` tabelas `resultados_partido_secao` e `resultados_candidato_secao`
=> [dados]br_tse_eleicoes resultados_partido_secao|resultados_candidato_secao

models/br_ce_fortaleza_sefin_iptu/br_ce_fortaleza_sefin_iptu__face_quadra.sql, models/br_ce_fortaleza_sefin_iptu/schema.yml
=> [Bugfix] br_ce_fortaleza_sefin_iptu__face_quadra

models/br_inep_censo_escolar/br_inep_censo_escolar__turma.sql
Atualizando os metadados. Em prod vai só até 2022 e em dev até 2023. O motivo é que estamos aguardando o pedido LAI para liberar 2023 em prod
=> [bugfix]: fix date partition br_inep_censo_escolar.turma

models/br_ms_sia/br_ms_sia__dicionario.sql
Este PR adiciona a coluna id_processamento_ambulatorial no dicionário do conjunto br_ms_sia
=> [Dbt] br_ms_sia.dicionario

models/br_bcb_agencia/br_bcb_agencia__agencia.sql
Este PR retira post_hook e atualiza lógica de materialização incremental de br_bcb_agencia.agencia
=> [Refactor] br_bcb_agencia

models/br_me_cnpj/br_me_cnpj__empresas.sql, models/br_me_cnpj/br_me_cnpj__estabelecimentos.sql
Este PR modifica a estratégia de materialização incremental do modelo dbt de insert+overwrite para merge
=> [Refactor] br_me_cnpj

models/br_stf_corte_aberta/br_stf_corte_aberta__decisoes.sql
- Alterando a typagem das colunas de datas.
=> [FixBug] br_stf_corte_aberta

models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__bolsa_familia_pagamento.sql
- Cris percebeu que a consulta estava bem alta, adicionou novos campos de cluster para conseguirmos reduzir.
- Segundo a Cris, melhorou um pouco o custo da consulta.
=> [fix] | `br_cgu_beneficios_cidadao.bolsa_familia_pagamento`

models/br_tse_eleicoes/code/[dbt]br_tse_eleicoes.ipynb
Adicionado códigos utilizados no tratamento das tabelas do TSE 2024.
Códigos não estão perfeitamente finalizados e revisados. Mas tem potencial de auxilio no tratamento das tabelas.
Posso está atualizando esses códigos e documentando melhor o processo posteriormente
=> [Docs]Subir codigos de tratamento TSE

models/br_me_cnpj/br_me_cnpj__dicionario.sql
- Este PR atualiza o dicionário do conjunto br_me_cnpj
=> bugfix: update br_me_cnpj dicionario

models/br_inpe_prodes/br_inpe_prodes__municipio_bioma.sql, models/br_inpe_prodes/code/clean_data.py, models/br_inpe_prodes/code/download_data.py
- Consertando a typagem referente a `area_total`
- OBS: Ainda não há dados ainda de 2024.
=> [BugFix] br_inpe_prodes

dbt_project.yml, models/br_cgu_orcamento_publico/br_cgu_orcamento_publico__orcamento.sql, models/br_cgu_orcamento_publico/schema.yml, models/br_cgu_receitas_publicas/br_cgu_receitas_publicas__receitas.sql, models/br_cgu_receitas_publicas/schema.yml
- Subindo os Dados de Receitas Públicas e Orçamento Público
=> [dbt] br_cgu_receitas_publicas l br_cgu_orcamento_publico

models/br_rf_cafir/br_rf_cafir__imoveis_rurais.sql
- Este PR remove configs desnecessárias do modelo dbt
=> [Refactor] br_rf_cafir

models/br_me_rais/br_me_rais__microdados_estabelecimentos.sql, models/br_me_rais/br_me_rais__microdados_vinculos.sql
- Removendo o incremental para atualizar o ano de 2023 com os dados completos
=> [Dbt] br_me_rais

CONTRIBUTING.md, README.md
A nomeação de cada Pull Request (PR) deve seguir o seguinte padrão:
- O título de cada Pull Request (PR) deve começar com uma das seguintes palavras-chave, entre colchetes. Além disso, **marque a palavra-chave que melhor descreve o seu PR atual**:
PR Referente a issue #890 Foi atualizado o README-md e adicionado CONTRIBUTING.md.
=> [Docs] Atualizando README.md e criando CONTRIBUTING.md

.github/workflows/cd.yaml
PR referente a issue #900 
Para facilitar contribuições futuras esse script foi alterado com:
```yaml
on:
push:
branches: [main]
``` 
Onde esperamos acontecer um push na branch `main`  e executamos a [action][action] usando ela como ambiente.
[action]: https://github.com/basedosdados/queries-basedosdados/actions/workflows/cd.yaml
=> [Refactor] Alterar cd.yaml para ativar em push on 'main'

dbt_project.yml, models/world_imdb_movies/code/main.ipynb, models/world_imdb_movies/schema.yml, models/world_imdb_movies/world_imdb_movies__top_movies_per_year.sql
- Subindo os dados de filmes da IMDb.
=> [Data] world_imdb_movies.top_movies_per_year

models/br_rf_cno/br_rf_cno__areas.sql, models/br_rf_cno/br_rf_cno__cnaes.sql, models/br_rf_cno/br_rf_cno__microdados.sql, models/br_rf_cno/br_rf_cno__vinculos.sql
- Atualiza permissionamento em br_rf_cno
=> [Feature] br_rf_cno

models/br_ms_cnes/br_ms_cnes__profissional.sql
Conserta erros de data nula na fonte original
=> [BugFix] br_ms_cnes.profissional

models/br_inpe_queimadas/br_inpe_queimadas__microdados.sql, models/br_inpe_queimadas/schema.yaml
Descrição do PR:
Arquitetura -> [🏗️](https://docs.google.com/spreadsheets/d/1MbiG41gS8lWuO9S-1V0w708uOY2gz07OJ70gL3CfWZw/edit?pli=1&gid=0#gid=0) 
Ordenar as colunas conforme o guia -> [🗺️](https://basedosdados.github.io/sdk/style_data/#ordenamento-de-variaveis) 
- ano
- mês 
- data_hora
- bioma
- sigla_uf,
- id_municipio
- latitude
- longitude
- satelite
- (....)
=> [fix] Organizar ordem das colunas - br_inpe_queimadas.microdados

models/br_me_caged/br_me_caged__microdados_movimentacao.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_excluida.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_fora_prazo.sql, models/br_me_caged/schema.yml
- Este PR atualiza os modelos do caged
1. Como funcionam os ajustes?
Lógica: as tabelas fora_prazo e excluida contém saldos que precisam ser adicionados e/ou retirados da série.
- A variável competenciamov, identifica o ano-mes que o saldo deve ser modificado na tabela microdados_movimentacao.
- todas as tabelas tem competenciamov  e competenciadec 
- para a tabela microdados_movimentacao, todos os valores de linha são iguais entre competenciadec e competenciamov. A interpretação é: as movimentações foram declaradas na data de competÊncia. 
microdados_movimentacao_fora_prazo
- Em 2023-06 (competencaidec) foi declarado uma movimentacao referente a 202206 (competenciamov)
- para ajustar, basta adicionar saldos com competenciamov. isso garante que todos os saldos adicionados fora do prazo …
=> [fix] br_me_caged

models/br_me_caged/br_me_caged__microdados_movimentacao.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_excluida.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_fora_prazo.sql
- Roda tabble approve novamente para corrigir problemas no schema dos dados
=> [refactor] br_me_caged

models/br_me_caged/br_me_caged__microdados_movimentacao.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_excluida.sql, models/br_me_caged/br_me_caged__microdados_movimentacao_fora_prazo.sql
- Roda o tabble approve para materializar tabelas do caged em produção
=> [BugFix] br_me_caged

models/br_camara_dados_abertos/br_camara_dados_abertos__despesa.sql
- Subindo o ano de 2023 que está desatualizado.
=> [BugFix] br_camara_dados_abertos.despesa

models/br_me_cnpj/br_me_cnpj__empresas.sql, models/br_me_cnpj/br_me_cnpj__estabelecimentos.sql
Reverts basedosdados/queries-basedosdados#959 para o modelo DBT de execução com a estratégia de materialização padrão
=> Revert "[bugfix] br_me_cnpj"

models/br_me_rais/br_me_rais__dicionario.sql
- Table Approve no dicionário da RAIS
=> [Table-Approve] br_me_rais

models/br_me_rais/br_me_rais__microdados_vinculos.sql
-  Retornando para o modelo incremental e já adicionando o modelo is_incremental para subir a tabela de 2024.
=> [BugFix] br_me_rais
